AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template allows Ermetic SaaS to establish trust i.e. perform actions (as per permissions policy) with this managed account
Parameters:
  ErmeticAccountId:
    Description: 12 digit AWS Account ID of Ermetic. Ermetic establishes trust with monitored accounts to perform actions as defined by a permissions policy.
    Type: String
    Default: "081802104111"
Resources:
  ErmeticRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${ErmeticAccountId}:root"
            Action:
              - sts:AssumeRole
      RoleName: IAM_R_ERMETIC_SECURITY_XA
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
