AWSTemplateFormatVersion: 2010-09-09
Description: Ermetic AWS Control Tower managed account template

# ---------------------------------------------------------------------------------------------------------------
#
#   This template creates the Ermetic Integration IAM role in a Control Tower managed account.
#
# ---------------------------------------------------------------------------------------------------------------

Parameters:
  ErmeticAccountId:
    Description: Ermetic AWS Account ID (12 digits).
    Type: String
    Default: "081802104111"
  ErmeticExternalId:
    AllowedPattern: .+
    ConstraintDescription: ErmeticExternalId is required
    Description: Ermetic external ID
    Type: String

Resources:
  ErmeticRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${ErmeticAccountId}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ErmeticExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: ReadOnly
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:Describe*
                  - batch:Describe*
                  - batch:List*
                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudtrail:Describe*
                  - cloudtrail:Get*
                  - cloudtrail:List*
                  - cloudtrail:LookupEvents
                  - cloudwatch:Describe*
                  - cloudwatch:GetMetric*
                  - cloudwatch:ListMetrics
                  - config:Describe*
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - ec2:Describe*
                  - ecr:Describe*
                  - ecr:GetRepositoryPolicy
                  - ecr:StartImageScan
                  - ecr:List*
                  - ecr-public:Describe*
                  - ecr-public:GetRepositoryPolicy
                  - ecr-public:List*
                  - ecs:Describe*
                  - ecs:List*
                  - eks:Describe*
                  - eks:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticbeanstalk:Describe*
                  - elasticbeanstalk:List*
                  - elasticloadbalancing:Describe*
                  - es:Describe*
                  - es:List*
                  - iam:Generate*
                  - iam:Get*
                  - iam:List*
                  - identitystore:Describe*
                  - kms:Describe*
                  - kms:GetKey*
                  - kms:List*
                  - lambda:Get*Policy
                  - lambda:List*
                  - logs:Describe*
                  - organizations:Describe*
                  - organizations:List*
                  - redshift:Describe*
                  - redshift:List*
                  - rds:Describe*
                  - rds:List*
                  - s3:Describe*
                  - s3:GetAccessPoint*
                  - s3:GetAccountPublicAccessBlock
                  - s3:GetBucket*
                  - s3:GetEncryptionConfiguration
                  - s3:GetJobTagging
                  - s3:ListAccessPoints
                  - s3:ListAllMyBuckets
                  - s3:ListBucketVersions
                  - s3:ListJobs
                  - secretsmanager:Describe*
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:List*
                  - sns:Get*
                  - sns:List*
                  - sqs:Get*
                  - sqs:List*
                  - ssm:Describe*
                  - ssm:List*
                  - sso:Describe*
                  - sso:Get*
                  - sso:List*
                  - sso-directory:List*
                  - sso-directory:Search*
                  - sts:DecodeAuthorizationMessage
                  - tag:Get*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: arn:aws:s3:::elasticbeanstalk-*
              - Effect: Allow
                Action: apigateway:Get*
                NotResource: arn:aws:apigateway:*::/apikeys*
      RoleName: ErmeticRole
